// <auto-generated />
using GrpcServiceTestTaskAdvantica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcServiceTestTaskAdvantica.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230904212010_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcServiceTestTaskAdvantica.Data.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Birthday")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("HaveChildren")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Worker");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = 627670080000000000L,
                            FirstName = "Ivan",
                            HaveChildren = false,
                            LastName = "Ivanov",
                            MiddleName = "Ivanovich",
                            Sex = 1
                        },
                        new
                        {
                            Id = 2,
                            Birthday = 627145632000000000L,
                            FirstName = "Petr",
                            HaveChildren = true,
                            LastName = "Petrov",
                            MiddleName = "Petrovich",
                            Sex = 1
                        },
                        new
                        {
                            Id = 3,
                            Birthday = 621412992000000000L,
                            FirstName = "Nika",
                            HaveChildren = false,
                            LastName = "Niloaeva",
                            MiddleName = "Nikolaebna",
                            Sex = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
